#!/bin/bash

# simple BLE COVID-19 advertising via Bluetooth 4 adapter
# Slawomir Jasek <slawomir.jasek@smartlockpicking.com>

# BLE adapter, adjust to your one (confirm with hciconfig)
HCI=hci0

# should be encrypted according to spec, we just fill static dummy value
META="01 5C 00 00"

hciconfig $HCI up
#stop scanning (in case the adapter busy)
hciconfig $HCI noscan
# set advertising parameters (100ms)
hcitool -i $HCI cmd 0x08 0x0006 A0 00 A0 00 03 00 00 00 00 00 00 00 00 07 00

COUNT=0;
# send 255 various IDs
while [ $COUNT -lt 255 ]; do
    HEX=`printf '%02X' $COUNT`
#    HEXCOUNT=${hex:0:2}" "${hex:2:2}
    ID="$HEX 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F"

    echo "====== Advertising: $ID ========= " 

    #set advertising payload
    hcitool -i $HCI cmd 0x08 0x0008 1F 02 01 1A 03 03 6F FD 17 16 6F FD $ID $META
    #start advertising
    hcitool -i $HCI cmd 0x08 0x000a 01

    COUNT=$((COUNT+1))
    sleep 1
done
